[versions]
android-gradle-plugin = "7.3.1"
androidxLifecycleViewModel = "2.5.1"
coroutines = "1.7.3"
kotlin-gradle-plugin = "1.8.0"
ktlint = "0.48.2"
koin = "3.2.2"
mockative = "2.0.1"
napier = "2.6.1"
turbine = "1.0.0"

[libraries]
# android
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycleViewModel" }
# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
# kotlin
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
# ktlint
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
# logging
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
# Tests
testdependencies-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
testdependencies-koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
testdependencies-mockative = { module = "io.mockative:mockative", version.ref = "mockative" }
testdependencies-mockative-processor = { module = "io.mockative:mockative-processor", version.ref = "mockative" }
testdependencies-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
testDependencies = [
    "testdependencies-coroutinesTest",
    "testdependencies-koin-test",
    "testdependencies-mockative",
    "testdependencies-turbine",
]